export const phrases = [
  "Em breve, uma só carne...",
  "Nosso amor, nossa maior bênção.",
  "Um só coração, uma só alma.",
  "Nossa aliança, nossa promessa.",
  "Unidos pelo amor, guiados pela fé.",
  "O início de um para sempre.",
  "O amor é o nosso alicerce.",
  "Nossa história, um plano divino.",
  "Dois caminhos, um só destino.",
  "Juntos, somos mais fortes.",
  "O amor é paciente, o amor é bondoso.",
  "A espera valerá a pena.",
  "Nossa casa será um lar de amor e paz.",
  "Nossos passos, uma só direção.",
  "Um laço que o tempo não desfaz.",
  "A melhor parte da vida começa agora.",
  "A jornada é nossa, a glória é de Deus.",
  "Em cada passo, o amor se renova.",
  "O amor é a nossa base sólida.",
  "Uma nova vida em Cristo Jesus.",
  "A espera fortalece o nosso amor.",
  "O amanhã será mais bonito que o hoje.",
  "Nossa felicidade é o reflexo da nossa fé.",
  "Caminhamos juntos, de mãos dadas.",
  "O amor que nos une é eterno.",
  "Dois corações, um só propósito.",
  "Nossa promessa é para toda a vida.",
  "O amor que Deus nos deu é perfeito.",
  "A partir daqui, tudo é para sempre.",
  "Nosso amor é a prova do cuidado de Deus.",
  "O caminho da vida nos uniu.",
  "Nosso amor foi escrito por Deus.",
  "Um paraíso, aqui e agora, com você.",
  "Para amar, honrar e cuidar.",
  "A nossa história, o nosso milagre.",
  "Um amor que transborda, uma vida a dois.",
  "No amor, encontramos nossa morada.",
  "Juntos, realizamos sonhos.",
  "A fé nos uniu, o amor nos fortalece.",
  "Uma nova página em nosso livro.",
  "Nossa vida, um presente mútuo.",
  "Um amor que nos faz crescer.",
  "Com você, a vida é uma oração.",
  "Nossa união, uma benção sem fim.",
  "O nosso sim será um eco do céu.",
  "Com Deus no centro, tudo se completa.",
  "A eternidade começa com você.",
  "Para sempre é o nosso ponto de partida."
];
