export const phrases = [
  "Rumo a Luís Eduardo Magalhães!",
  "Nossa primeira aventura oficial na estrada.",
  "LEM, aí vamos nós!",
  "Finalmente 240 horas coladinhos.",
  "10 dias de 'bom dia' e 'boa noite' juntos.",
  "A contagem regressiva para 10 noites sem hora para ir embora.",
  "Ansiedade a mil para dormir e acordar ao seu lado.",
  "Hora de apresentar a mulher da minha vida para a família.",
  "Foi difícil, mas o nosso 'nós' venceu.",
  "A viagem vai acontecer!",
  "Lutamos por esses dias, vamos aproveitar cada km.",
  "Contra todas as probabilidades: O carro vai pegar a estrada!",
  "Ansiosos pela nossa primeira viagem juntos.",
  "Dormir de conchinha por 10 dias seguidos.",
  "Levando o amor para conhecer o sertão.",
  "Nossa primeira 'lua de mel' antecipada.",
  "Estrada, música e nós dois.",
  "Cada quilômetro nos aproxima mais.",
  "Vai valer a pena cada segundo dessa espera.",
  "O destino é LEM, mas a jornada é nossa.",
  "Dez dias para sermos apenas nós.",
  "O início das nossas memórias pelo mundo.",
  "Nosso noivado ganhando estrada.",
  "Corações ansiosos, malas prontas.",
  "Finalmente sós, finalmente nós.",
  "Cada instante juntos será eterno.",
  "Dez dias de sonho real.",
  "Nossa história ganha um novo capítulo em LEM."
];
